# Generated by Django 3.1.1 on 2021-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0004_auto_20210425_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='minimum_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
