# Generated by Django 3.1.1 on 2021-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0008_auto_20210506_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField(default=False)),
            ],
        ),
    ]
