# Generated by Django 3.1.1 on 2021-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0009_selectcamera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=100),
        ),
    ]
