# Generated by Django 3.1.1 on 2021-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0012_auto_20210602_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_weight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_weight_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vehicle_weight_flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
