# Generated by Django 3.1.1 on 2021-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0013_auto_20210603_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vehicle_second_weight_flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
