# Generated by Django 3.1.1 on 2021-06-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0015_auto_20210604_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ware_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yard.warehouse'),
        ),
    ]
