# Generated by Django 3.1.1 on 2021-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0016_auto_20210604_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
    ]
