# Generated by Django 3.1.1 on 2021-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0017_logo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
