# Generated by Django 3.1.1 on 2021-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0020_auto_20210609_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpcred',
            name='sender_address',
            field=models.EmailField(default='admin@admin.com', max_length=254),
            preserve_default=False,
        ),
    ]
