# Generated by Django 3.1.1 on 2021-06-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0021_smtpcred_sender_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
