# Generated by Django 3.1.1 on 2021-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0023_total_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_camera',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
