# Generated by Django 3.1.1 on 2021-06-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0025_barrier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total_camera',
        ),
        migrations.AddField(
            model_name='barrier',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='selectcamera',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='barrier',
            field=models.BooleanField(default=False),
        ),
    ]
