# Generated by Django 3.1.1 on 2021-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0029_auto_20210617_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='heading',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
