# Generated by Django 3.1.1 on 2021-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0030_auto_20210618_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='heading',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
