# Generated by Django 3.1.1 on 2021-06-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0031_auto_20210621_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yard.container'),
        ),
    ]
