# Generated by Django 3.1.1 on 2021-06-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0033_combination_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
