# Generated by Django 3.1.1 on 2021-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0034_auto_20210623_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
