# Generated by Django 3.1.1 on 2021-06-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0035_containershow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='name2',
        ),
        migrations.AlterField(
            model_name='customer',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Company', 'Company')], max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Company', 'Company')], max_length=10),
        ),
    ]
