# Generated by Django 3.1.1 on 2021-06-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0037_auto_20210629_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
