# Generated by Django 3.1.1 on 2021-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0038_showtonne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Io',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
