# Generated by Django 3.1.1 on 2021-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0039_io'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
