# Generated by Django 3.1.1 on 2021-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0042_foreignweigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignweigh',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
