# Generated by Django 3.1.1 on 2021-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0043_foreignweigh_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignweigh',
            name='first_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='foreignweigh',
            name='net_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='foreignweigh',
            name='second_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='foreignweigh',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
