# Generated by Django 3.1.1 on 2021-07-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0044_auto_20210702_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
