# Generated by Django 3.1.1 on 2021-07-06 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0045_foreignflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='ss_role_access',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
