# Generated by Django 3.1.1 on 2021-07-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0048_auto_20210713_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yard.transaction'),
        ),
    ]
