# Generated by Django 3.1.1 on 2021-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0049_combination_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='combination_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
