# Generated by Django 3.1.1 on 2021-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yard', '0053_auto_20210715_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='agreed_value',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='article',
        ),
        migrations.AddField(
            model_name='contract',
            name='required_materials',
            field=models.JSONField(
                default=[{'agreed_value': 65500, 'material': 1}, {'agreed_value': 64500, 'material': 2}]),
            preserve_default=False,
        ),
    ]
