# Generated by Django 3.1.1 on 2021-07-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0055_auto_20210716_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yard.contract'),
        ),
    ]
