# Generated by Django 3.1.1 on 2021-07-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0056_transaction_contract_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yard.supplier')),
                ('yard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yard.yard_list')),
            ],
        ),
    ]
