# Generated by Django 3.1.1 on 2021-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0058_auto_20210729_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquality',
            name='quality',
            field=models.CharField(choices=[('Quality_A', 'Quality A'), ('Quality_B', 'Quality B'), ('Quality_C', 'Quality C')], max_length=100),
        ),
    ]
