# Generated by Django 3.1.1 on 2021-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0059_auto_20210729_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquality',
            name='Fertilizer',
            field=models.CharField(choices=[('A_Grade', 'A_Grade'), ('B_Grade', 'B_Grade'), ('C_Grade', 'C_Grade')], max_length=100),
        ),
        migrations.AlterField(
            model_name='materialquality',
            name='quality',
            field=models.CharField(choices=[('Quality_A', 'Quality_A'), ('Quality_B', 'Quality_B'), ('Quality_C', 'Quality_C')], max_length=100),
        ),
    ]
