# Generated by Django 3.1.1 on 2021-07-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0060_auto_20210729_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquality',
            name='Fertilizer',
            field=models.CharField(choices=[('A Grade', 'A Grade'), ('B Grade', 'B Grade'), ('C Grade', 'C Grade')], max_length=100),
        ),
        migrations.AlterField(
            model_name='materialquality',
            name='quality',
            field=models.CharField(choices=[('Quality A', 'Quality A'), ('Quality B', 'Quality B'), ('Quality C', 'Quality C')], max_length=100),
        ),
    ]
