# Generated by Django 3.1.1 on 2021-06-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yard', '0030_auto_20210618_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_spacing', models.FloatField(blank=True, null=True)),
                ('row_spacing', models.FloatField(blank=True, null=True)),
                ('crop_spacing_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('row_spacing_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('planting_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('yield_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('planting_area', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yard.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('long_lat', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_datetime', models.DateTimeField(null=True)),
                ('lab_test_datetime', models.DateTimeField(blank=True, null=True)),
                ('result_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.crop')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.location')),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantAnalysisCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('max_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
                ('plant_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.plantanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='CropTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
                ('holiday_management', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(max_length=100, null=True)),
                ('crop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.crop')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.location')),
            ],
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('crop_spacing', models.FloatField(blank=True, null=True)),
                ('row_spacing', models.FloatField(blank=True, null=True)),
                ('crop_spacing_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('row_spacing_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('iso_8601', models.BooleanField(default=False, null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.crop')),
                ('locations', models.ManyToManyField(blank=True, to='agri.Location')),
            ],
        ),
    ]
