# Generated by Django 3.1.1 on 2021-06-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantanalysis',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='plantanalysis',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
