# Generated by Django 3.1.1 on 2021-06-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_auto_20210623_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('collection_datetime', models.DateTimeField(null=True)),
                ('lab_test_datetime', models.DateTimeField(blank=True, null=True)),
                ('result_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.location')),
            ],
        ),
        migrations.CreateModel(
            name='SoilTexture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('clay_composition', models.FloatField(blank=True, null=True)),
                ('sand_composition', models.FloatField(blank=True, null=True)),
                ('silt_composition', models.FloatField(blank=True, null=True)),
                ('collection_datetime', models.DateTimeField(null=True)),
                ('lab_test_datetime', models.DateTimeField(blank=True, null=True)),
                ('result_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.location')),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTextureCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('max_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_texture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.soiltexture')),
            ],
        ),
        migrations.AddField(
            model_name='soiltexture',
            name='soil_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.soiltype'),
        ),
        migrations.CreateModel(
            name='SoilAnalysisCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('max_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.soilanalysis')),
            ],
        ),
    ]
