# Generated by Django 3.1.1 on 2021-07-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0007_auto_20210629_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('max_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_permissible_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantanalysiscriteria',
            name='max_permissible_value',
        ),
        migrations.RemoveField(
            model_name='plantanalysiscriteria',
            name='min_permissible_value',
        ),
        migrations.RemoveField(
            model_name='plantanalysiscriteria',
            name='title',
        ),
        migrations.RemoveField(
            model_name='plantanalysiscriteria',
            name='value',
        ),
        migrations.RemoveField(
            model_name='soilanalysiscriteria',
            name='max_permissible_value',
        ),
        migrations.RemoveField(
            model_name='soilanalysiscriteria',
            name='min_permissible_value',
        ),
        migrations.RemoveField(
            model_name='soilanalysiscriteria',
            name='title',
        ),
        migrations.RemoveField(
            model_name='soilanalysiscriteria',
            name='value',
        ),
        migrations.RemoveField(
            model_name='soiltexturecriteria',
            name='max_permissible_value',
        ),
        migrations.RemoveField(
            model_name='soiltexturecriteria',
            name='min_permissible_value',
        ),
        migrations.RemoveField(
            model_name='soiltexturecriteria',
            name='title',
        ),
        migrations.RemoveField(
            model_name='soiltexturecriteria',
            name='value',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='plantanalysiscriteria',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.criteria'),
        ),
        migrations.AddField(
            model_name='soilanalysiscriteria',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.criteria'),
        ),
        migrations.AddField(
            model_name='soiltexturecriteria',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.criteria'),
        ),
    ]
