# Generated by Django 3.1.1 on 2021-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0008_auto_20210701_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantanalysis',
            name='collection_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantanalysis',
            name='lab_test_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantanalysis',
            name='result_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soilanalysis',
            name='collection_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soilanalysis',
            name='lab_test_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soilanalysis',
            name='result_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soiltexture',
            name='collection_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soiltexture',
            name='lab_test_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soiltexture',
            name='result_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
