# Generated by Django 3.1.1 on 2021-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0010_auto_20210701_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantanalysiscriteria',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='soilanalysiscriteria',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='soiltexturecriteria',
            name='criteria',
        ),
        migrations.AddField(
            model_name='plantanalysiscriteria',
            name='max_permissible_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantanalysiscriteria',
            name='min_permissible_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantanalysiscriteria',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='plantanalysiscriteria',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilanalysiscriteria',
            name='max_permissible_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilanalysiscriteria',
            name='min_permissible_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilanalysiscriteria',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='soilanalysiscriteria',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltexturecriteria',
            name='max_permissible_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltexturecriteria',
            name='min_permissible_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltexturecriteria',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='soiltexturecriteria',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
