# Generated by Django 3.1.1 on 2021-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0011_auto_20210704_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
