# Generated by Django 3.1.1 on 2021-07-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0012_auto_20210706_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('min_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('max_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('night_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('evn_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('morn_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('dew_point', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('clouds', models.CharField(blank=True, max_length=50, null=True)),
                ('rain', models.CharField(blank=True, max_length=50, null=True)),
                ('pop', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.location')),
            ],
        ),
    ]
