# Generated by Django 3.1.1 on 2021-07-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0013_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
