# Generated by Django 3.1.1 on 2021-07-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0014_weather_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
