# Generated by Django 3.1.1 on 2021-07-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0015_weather_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='pop',
        ),
    ]
