# Generated by Django 3.1.1 on 2021-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_app', '0002_auto_20210701_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
